name: Frontend Continuous Integration Pipeline

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
      - '.env.example'
      - '.github/*.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
      - '.env.example'
      - '.github/*.md'

env:
  NODE_VERSION: '16'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Run tests with coverage
        run: |
          mkdir -p coverage
          npm run test:coverage
          ls -la coverage/
      
      - name: Debug coverage directory
        run: |
          echo "Listing coverage directory:"
          ls -la coverage/ || echo "Coverage directory not found"
          echo "Current directory:"
          pwd
          echo "Directory structure:"
          find . -name "lcov.info"
      
      - name: Setup Code Climate
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Run Code Climate Analysis
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          COVERAGE_FILE=$(find . -name "lcov.info" -not -path "./node_modules/*" | head -n 1)
          if [ -n "$COVERAGE_FILE" ]; then
            echo "Found coverage file at: $COVERAGE_FILE"
            ./cc-test-reporter format-coverage "$COVERAGE_FILE" --input-type lcov
            ./cc-test-reporter upload-coverage
          else
            echo "Error: lcov.info not found in project directory (excluding node_modules)"
            exit 1
          fi